name: cmake

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

  multi_arch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm32v7, riscv64]

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: CMake and CTest
      run: |
          docker run "$PWD:/yyjson" ${{ matrix.arch }}/ubuntu bash -e -c '
            apt-get update
            apt-get install -y gcc g++ cmake
            mkdir build
            cd build
            cmake ../yyjson -DYYJSON_BUILD_TESTS=ON
            cmake --build . --config Release
            ctest -C Release --output-on-failure
          '
